### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by haydenholligan** [fulldecent/FDTextFieldTableViewCell#3]
CheckCocoapodsQualityIndex is failing due to lack of tests.  Needs to satisfy

`(total_text_expectations / lines_of_code) < 0.045`

**Comment by fulldecent** [comment]
The work plan for this issue to just to add a few test cases.

**Comment by yaroslav-zhurakovskiy** [comment]
I added some tests. Check out https://github.com/fulldecent/FDTextFieldTableViewCell/pull/7

**Comment by fulldecent** [comment]
thank you merged
